MOUSEKEY_ENABLE     = no     # Mouse keys
RGBLIGHT_ENABLE     = no    # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE   = yes
RGB_MATRIX_DRIVER   = WS2812
VIA_ENABLE          = no     # Enable VIA
OLED_DRIVER_ENABLE  = yes
LTO_ENABLE          = no
#BOOTLOADER			= qmk-dfu
USER_NAME := jumar
